### ISSUE TITLE
Error in loading

### ISSUE THREAD

**Issue by Creeper9207** [pfirsich/lua-discordRPC#1]
I attempted to load the sample file, but i'm not surte where "discord-rpc" in line 2 of discordRPC.lua is, could you please make a README? I am very interested in this project.

**Comment by pfirsich** [comment]
For some reason, this took so much longer than I wanted it to, but I added a readme now! Let me know if there is still stuff left unclear. Thanks for reminding me to add a readme to this project :)

**Comment by Creeper9207** [comment]
No problem! People who do work like you are the best people society has to offer.
