### ISSUE TITLE
Won't start using LOVE

### ISSUE THREAD

**Issue by vimaexd** [pfirsich/lua-discordRPC#3]
I am running the main.lua example with love, and it displays the following error

`
Error
discordRPC.lua:2: cannot load module 'discord-rpc;: %1 is not a valid Win32 application
`

I have my discord-rpc.dll file in the same folder as my main.lua.

OS = Windows 10 64bit
Editor = Sublime Text
Language = Lua
Engine = LOVE2d

**Comment by vimaexd** [comment]
I figured it out - i was using a version of love too new to run the code

**Comment by VMan-2002** [comment]
reopen this?

**Comment by pfirsich** [comment]
Someone commented on this, asking to reopen it and deleted their comment, so I will explain the problem:
etstringy was not using a version too new.
It works with 11.3 (and it did work with 11.1). You just have to make sure that if you are using 32-Bit löve, you use the 32 bit discord-rpc.dll and if you use 64-Bit löve, you use the 64-Bit discord-rpc.dll (like explained in the README too). If it doesn't match, you get that error.
