### ISSUE TITLE
I can't start the example script

### ISSUE THREAD

**Issue by LFGaming** [pfirsich/lua-discordRPC#8]
When I try to use the exmple script i get the following error
```
Error

boot.lua:577: Cannot load game at path 'C:/Users/micro/Documents/GitHub/lua-discordRPC/main.lua'.
Make sure a folder exists at the specified path.


Traceback

[C]: in function 'error'
[C]: in function 'xpcall'
[C]: in function 'xpcall'
```

I can't find out how to fix it, could someone help.
Thanks.

**Comment by pfirsich** [comment]
Pretty sure you are not starting your game correctly. Read this thoroughly: https://love2d.org/wiki/Getting_Started

**Comment by LFGaming** [comment]
That could very well be, but I now have a working one but without Löve. But still thanks. Shall i then close the issue?
