### ISSUE TITLE
ffi unable to load 'discord-rpc'

### ISSUE THREAD

**Issue by TimmyRB** [pfirsich/lua-discordRPC#9]
When I attempt to load this library, I get an error thrown out from the second line of `discordRPC.lua` telling me it couldn't find "discord-rpc".
This is my file structure
![image](https://user-images.githubusercontent.com/19505665/133720997-4bd4b3c8-e369-4b0f-a268-cfbd2eeabfeb.png)

And this is the error
![image](https://user-images.githubusercontent.com/19505665/133721017-b9437fd4-e3c2-49be-a9a9-1a1bf5edd8b0.png)

I'm quite new to LuaJIT and any help is appreciated!

**Comment by pfirsich** [comment]
I don't think your problem is related to this library and I also can't help you debug effectively, because I don't use Windows anymore. Considering that it's very unlikely anyone else will see or comment this issue, I will close it. Sorry!
